{% set name = "libm2k" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/analogdevicesinc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd5e4b4169d2d0f6dbf381dd10effb28ca1c58c85ff77ad9145a04906db53431
  patches:
    - 0001-Don-t-set-a-specific-architecture-for-OSX.patch
    - 0002-Query-Python-EXT_SUFFIX-to-set-the-extension-suffix.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libm2k', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    # libudev CDT only needed for compiling against libiio on CentOS 6 sysroot
    - {{ cdt('libudev-devel') }}  # [linux and cdt_name=='cos6']
    - make  # [not win]
    - ninja  # [win]
    - swig
    # cross-compilation requirements
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - libiio
    - libusb-cos6  # [linux and cdt_name=='cos6']
    - python
    - setuptools
  run:
    # libiio run dep included by its run_exports
    - python

test:
  commands:
    # verify that executables can be run
    - m2kcli --help

    # verify that headers get installed
    - test -f $PREFIX/include/libm2k/m2k.hpp  # [not win]
    - if not exist %PREFIX%\\Library\\include\\libm2k\\m2k.hpp exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/libm2k${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\libm2k.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libm2k.lib exit 1  # [win]
  imports:
    - libm2k

about:
  home: https://github.com/analogdevicesinc/libm2k
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Library for interfacing with the ADALM2000
  description: |
    C++ library and python bindings for interfacing with
    the ADALM2000 portable lab. This library simplifies
    ADALM2000's functionality into a series of easy to
    use components.
  doc_url: https://analogdevicesinc.github.io/libm2k/
  dev_url: https://github.com/analogdevicesinc/libm2k

extra:
  recipe-maintainers:
    - ryanvolz
    - tfcollins
